wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1679311374.13132
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.9.15
      5: 0.13.10
      8:
      - 3
      - 5
bpe:
  desc: null
  value:
    model_path: yttm.bpe
    train: true
dataset:
  desc: null
  value:
    name: ljspeech
    root: DB/LJspeech
    sample_rate: 22050
    train_part: 0.95
model:
  desc: null
  value:
    feat_in: 64
    vocab_size: 120
train:
  desc: null
  value:
    batch_size: 32
    clip_grad_norm: 15
    epochs: 42
    num_workers: 1
    optimizer:
      lr: 0.0005
      weight_decay: 0.0001
    seed: 42
wandb:
  desc: null
  value:
    log_interval: 20
    project: quartznet_ljspeech
